sonar.projectKey=prm393_lab3
sonar.projectName=PRM393 Lab 3 - Journal Trend Analyzer
sonar.projectVersion=1.0

sonar.sources=lib/
sonar.tests=test/
sonar.exclusions=**/*.g.dart,**/generated/**,**/android/**,**/ios/**,**/build/**
sonar.sourceEncoding=UTF-8
sonar.dart.coverage.reportPath=coverage/lcov.info
